# Generated by Django 3.2.6 on 2021-09-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('shop', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'), max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('detials', models.TextField()),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proimage', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('shop_name', models.CharField(max_length=150)),
                ('Business_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
    ]
