# Generated by Django 3.2.6 on 2021-10-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
