# Generated by Django 3.2.6 on 2021-10-08 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_sellerprofile_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
