# Generated by Django 3.2.6 on 2021-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending'), ('out for delivery', 'out for delivery')], default='pending', max_length=1000),
        ),
    ]
